version: "3"
services:
  kofi-discord-webhook:
    hostname: "kofi-discord-webhook"
    container_name: "kofi-discord-webhook"
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=Europe/Berlin"
      - "PORT=3033"
      - "DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks"
      - "KOFI_VERIFICATION_TOKEN=myToken"
      - "NODE_ENV=production"
      - "DEBUG=true"
      - "LANGUAGE=de"
      # Custom Ko-fi name example (uncomment to use)
      # - "KOFI_NAME=BuyMeACoffee"
      # - "KOFI_LOGO=https://your-custom-logo-url.com/logo.png"
      # - "WEBHOOK_USERNAME=BuyMeACoffee Alert"
    networks:
      - proxy
    ports:
      - "3033:3033"
    image: "ghcr.io/cyb3rgh05t/kofi-discord-webhook:latest"
    restart: "unless-stopped"
    volumes:
      - "/opt/appdata/kofi-discord-webhook/config:/app/config"
      - "/opt/appdata/kofi-discord-webhook/logs:/app/logs"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://0.0.0.0:3033/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
networks:
  proxy:
    driver: bridge
    external: true
